file1 = {
    "kind": "Listing",
    "data": {
      "after": None,
      "dist": 2,
      "modhash": "srwj8cob0d67afeeb59867447f393b38e6bb67e1c269eede3b",
      "geo_filter": "",
      "children": [
        {
          "kind": "t5",
          "data": {
            "user_flair_background_color": None,
            "submit_text_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;Are you about to post a question to ask for help? Check out &lt;a href=\"/r/learnpython\"&gt;r/learnpython&lt;/a&gt;.  Also, for advanced topics hit up &lt;a href=\"/r/advancedpython\"&gt;r/advancedpython&lt;/a&gt;.&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
            "restrict_posting": True,
            "user_is_banned": False,
            "free_form_reports": True,
            "wiki_enabled": None,
            "user_is_muted": False,
            "user_can_flair_in_sr": None,
            "display_name": "pythonnews",
            "header_img": None,
            "title": "News about Python",
            "allow_galleries": True,
            "icon_size": None,
            "primary_color": "#004d7a",
            "active_user_count": None,
            "icon_img": "",
            "display_name_prefixed": "r/pythonnews",
            "accounts_active": None,
            "public_traffic": False,
            "subscribers": 129,
            "user_flair_richtext": [],
            "videostream_links_count": 0,
            "name": "t5_36a39",
            "quarantine": False,
            "hide_ads": False,
            "prediction_leaderboard_entry_type": 1,
            "emojis_enabled": False,
            "advertiser_category": "",
            "public_description": "A place to share and discuss python-centric news. \n\nUntil further notice, we are using the word \"news\" liberally, to include major releases for valuable projects, knowledge sharing articles, events in the community, plus anything anybody might actually call \"news\".  \n\nBe kind, don't spam, and we'll all be fine.   ",
            "comment_score_hide_mins": 0,
            "allow_predictions": False,
            "user_has_favorited": False,
            "user_flair_template_id": None,
            "community_icon": "",
            "banner_background_image": "",
            "original_content_tag_enabled": False,
            "community_reviewed": False,
            "submit_text": "Are you about to post a question to ask for help? Check out r/learnpython.  Also, for advanced topics hit up r/advancedpython.",
            "description_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;&lt;strong&gt;Python News Sites&lt;/strong&gt;\n- &lt;a href=\"https://www.python.org/blogs/\"&gt;Python Insider&lt;/a&gt;\n- &lt;a href=\"https://talkpython.fm/\"&gt;Talk Python&lt;/a&gt;\n- &lt;a href=\"https://realpython.com\"&gt;Real Python&lt;/a&gt;\n- &lt;a href=\"http://pyfound.blogspot.com/\"&gt;PSF&amp;#39;s PyFound Blog&lt;/a&gt;\n- &lt;a href=\"https://pycoders.com/\"&gt;PyCoder&amp;#39;s Weekly&lt;/a&gt;&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
            "spoilers_enabled": True,
            "comment_contribution_settings": {
  
            },
            "allow_talks": False,
            "header_size": None,
            "user_flair_position": "right",
            "all_original_content": False,
            "has_menu_widget": False,
            "is_enrolled_in_new_modmail": None,
            "key_color": "",
            "can_assign_user_flair": True,
            "created": 1422879908,
            "wls": None,
            "show_media_preview": True,
            "submission_type": "any",
            "user_is_subscriber": False,
            "allowed_media_in_comments": [],
            "allow_videogifs": True,
            "should_archive_posts": False,
            "user_flair_type": "text",
            "allow_polls": True,
            "collapse_deleted_comments": False,
            "emojis_custom_size": None,
            "public_description_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;A place to share and discuss python-centric news. &lt;/p&gt;\n\n&lt;p&gt;Until further notice, we are using the word &amp;quot;news&amp;quot; liberally, to include major releases for valuable projects, knowledge sharing articles, events in the community, plus anything anybody might actually call &amp;quot;news&amp;quot;.  &lt;/p&gt;\n\n&lt;p&gt;Be kind, don&amp;#39;t spam, and we&amp;#39;ll all be fine.   &lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
            "allow_videos": True,
            "is_crosspostable_subreddit": True,
            "suggested_comment_sort": None,
            "should_show_media_in_comments_setting": True,
            "can_assign_link_flair": True,
            "accounts_active_is_fuzzed": False,
            "allow_prediction_contributors": False,
            "submit_text_label": "",
            "link_flair_position": "right",
            "user_sr_flair_enabled": None,
            "user_flair_enabled_in_sr": False,
            "allow_discovery": True,
            "accept_followers": True,
            "user_sr_theme_enabled": True,
            "link_flair_enabled": True,
            "disable_contributor_requests": False,
            "subreddit_type": "restricted",
            "notification_level": None,
            "banner_img": "",
            "user_flair_text": None,
            "banner_background_color": "#006dad",
            "show_media": False,
            "id": "36a39",
            "user_is_contributor": False,
            "over18": False,
            "header_title": "",
            "description": "**Python News Sites**\n- [Python Insider](https://www.python.org/blogs/)\n- [Talk Python](https://talkpython.fm/)\n- [Real Python](https://realpython.com)\n- [PSF's PyFound Blog](http://pyfound.blogspot.com/)\n- [PyCoder's Weekly](https://pycoders.com/)\n",
            "submit_link_label": "",
            "user_flair_text_color": None,
            "restrict_commenting": False,
            "user_flair_css_class": None,
            "allow_images": True,
            "lang": "en",
            "whitelist_status": None,
            "url": "/r/pythonnews/",
            "created_utc": 1422879908,
            "banner_size": None,
            "mobile_banner_image": "",
            "user_is_moderator": False,
            "allow_predictions_tournament": False
          }
        },
        {
          "kind": "t5",
          "data": {
            "user_flair_background_color": None,
            "submit_text_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;Post your questions about your python code here, or ask for code review of your python code. &lt;/p&gt;\n\n&lt;p&gt;To learn how to format code check out FAQ  &lt;a href=\"http://www.reddit.com/r/learnpython/wiki/FAQ\"&gt;/r/learnpython/w/FAQ&lt;/a&gt;&lt;/p&gt;\n\n&lt;p&gt;If your code is too large, please use &lt;a href=\"http://gist.github.com\"&gt;http://gist.github.com&lt;/a&gt; or &lt;a href=\"http://pastebin.com\"&gt;http://pastebin.com&lt;/a&gt; for code hosting.&lt;/p&gt;\n\n&lt;p&gt;Please check the &lt;a href=\"http://www.reddit.com/r/learnpython/wiki/index\"&gt;wiki&lt;/a&gt; and &lt;a href=\"http://www.reddit.com/r/learnpython/wiki/FAQ\"&gt;FAQ&lt;/a&gt; before posting.&lt;/p&gt;\n\n&lt;p&gt;For posting python resources, use &lt;a href=\"/r/pythontips\"&gt;/r/pythontips&lt;/a&gt; or &lt;a href=\"/r/pythondojo\"&gt;/r/pythondojo&lt;/a&gt;\nFor general python discussion, use &lt;a href=\"/r/python\"&gt;/r/python&lt;/a&gt;\nTo find a programming buddy, use &lt;a href=\"/r/ProgrammingBuddies\"&gt;/r/ProgrammingBuddies&lt;/a&gt;\nTo show off your project, use &lt;a href=\"/r/madeinpython\"&gt;/r/madeinpython&lt;/a&gt;.&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
            "restrict_posting": True,
            "user_is_banned": False,
            "free_form_reports": True,
            "wiki_enabled": True,
            "user_is_muted": False,
            "user_can_flair_in_sr": None,
            "display_name": "learnpython",
            "header_img": "https://a.thumbs.redditmedia.com/QOLR_6JKHgnBEToB.png",
            "title": "Python Education",
            "allow_galleries": True,
            "icon_size": None,
            "primary_color": "#0079d3",
            "active_user_count": None,
            "icon_img": "",
            "display_name_prefixed": "r/learnpython",
            "accounts_active": None,
            "public_traffic": False,
            "subscribers": 809516,
            "user_flair_richtext": [],
            "name": "t5_2r8ot",
            "quarantine": False,
            "hide_ads": False,
            "prediction_leaderboard_entry_type": 2,
            "emojis_enabled": False,
            "advertiser_category": "",
            "public_description": "Subreddit for posting questions and asking for general advice about your python code.",
            "comment_score_hide_mins": 0,
            "allow_predictions": False,
            "user_has_favorited": False,
            "user_flair_template_id": None,
            "community_icon": "https://styles.redditmedia.com/t5_2r8ot/styles/communityIcon_jwr5s7l5ici61.png?width=256&amp;s=45deb6f123031525835c1ab234a53be00bdbc207",
            "banner_background_image": "",
            "original_content_tag_enabled": False,
            "community_reviewed": True,
            "submit_text": "Post your questions about your python code here, or ask for code review of your python code. \n\nTo learn how to format code check out FAQ  [/r/learnpython/w/FAQ](http://www.reddit.com/r/learnpython/wiki/FAQ)\n\nIf your code is too large, please use http://gist.github.com or http://pastebin.com for code hosting.\n\nPlease check the [wiki](http://www.reddit.com/r/learnpython/wiki/index) and [FAQ](http://www.reddit.com/r/learnpython/wiki/FAQ) before posting.\n\nFor posting python resources, use /r/pythontips or /r/pythondojo\nFor general python discussion, use /r/python\nTo find a programming buddy, use /r/ProgrammingBuddies\nTo show off your project, use /r/madeinpython.",
            "description_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;hr/&gt;\n\n&lt;blockquote&gt;\n&lt;p&gt;&lt;a href=\"#icon-information\"&gt;&lt;strong&gt;Rules&lt;/strong&gt;&lt;/a&gt;&lt;/p&gt;\n\n&lt;p&gt;1: Be polite&lt;/p&gt;\n\n&lt;p&gt;2: Posts to this subreddit must be requests for help learning python.&lt;/p&gt;\n\n&lt;p&gt;3: Replies on this subreddit must be pertinent to the question OP asked. &lt;/p&gt;\n\n&lt;p&gt;4: No replies copy / pasted from ChatGPT or similar.  &lt;/p&gt;\n\n&lt;p&gt;5: No advertising. No blogs/tutorials/videos/books/recruiting attempts.&lt;/p&gt;\n\n&lt;p&gt;This means no posts advertising blogs/videos/tutorials/etc, no recruiting/hiring/seeking others posts. We&amp;#39;re here to help, not to be advertised to. &lt;/p&gt;\n\n&lt;p&gt;Please, no &amp;quot;hit and run&amp;quot; posts, if you make a post, engage with people that answer you. Please do not delete your post after you get an answer, others might have a similar question or want to continue the conversation.&lt;/p&gt;\n&lt;/blockquote&gt;\n\n&lt;hr/&gt;\n\n&lt;blockquote&gt;\n&lt;p&gt;&lt;a href=\"#icon-information\"&gt;&lt;strong&gt;Learning resources&lt;/strong&gt;&lt;/a&gt;&lt;/p&gt;\n\n&lt;p&gt;Wiki and FAQ: &lt;a href=\"http://www.reddit.com/r/learnpython/wiki/index\"&gt;/r/learnpython/w/index&lt;/a&gt;&lt;/p&gt;\n&lt;/blockquote&gt;\n\n&lt;hr/&gt;\n\n&lt;blockquote&gt;\n&lt;p&gt;&lt;a href=\"#icon-comments\"&gt;&lt;strong&gt;Discord&lt;/strong&gt;&lt;/a&gt;&lt;/p&gt;\n\n&lt;p&gt;&lt;a href=\"https://discord.gg/python\"&gt;Join the Python Discord chat&lt;/a&gt;&lt;/p&gt;\n&lt;/blockquote&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
            "spoilers_enabled": False,
            "comment_contribution_settings": {
              "allowed_media_types": None
            },
            "allow_talks": False,
            "header_size": [170, 40],
            "user_flair_position": "right",
            "all_original_content": False,
            "has_menu_widget": False,
            "is_enrolled_in_new_modmail": None,
            "key_color": "#24a0ed",
            "can_assign_user_flair": False,
            "created": 1254499181,
            "wls": 6,
            "show_media_preview": False,
            "submission_type": "self",
            "user_is_subscriber": False,
            "allowed_media_in_comments": [],
            "allow_videogifs": False,
            "should_archive_posts": False,
            "user_flair_type": "text",
            "allow_polls": False,
            "collapse_deleted_comments": True,
            "emojis_custom_size": None,
            "public_description_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;Subreddit for posting questions and asking for general advice about your python code.&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
            "allow_videos": False,
            "is_crosspostable_subreddit": None,
            "suggested_comment_sort": None,
            "should_show_media_in_comments_setting": True,
            "can_assign_link_flair": False,
            "accounts_active_is_fuzzed": False,
            "allow_prediction_contributors": False,
            "submit_text_label": "",
            "link_flair_position": "right",
            "user_sr_flair_enabled": None,
            "user_flair_enabled_in_sr": False,
            "allow_discovery": True,
            "accept_followers": True,
            "user_sr_theme_enabled": True,
            "link_flair_enabled": True,
            "disable_contributor_requests": False,
            "subreddit_type": "public",
            "notification_level": None,
            "banner_img": "",
            "user_flair_text": None,
            "banner_background_color": "#3776ab",
            "show_media": False,
            "id": "2r8ot",
            "user_is_contributor": False,
            "over18": False,
            "header_title": "High res image: imgur.com/rkf2abW",
            "description": "*****************************\n\n&gt; [**Rules**](#icon-information)\n&gt; \n&gt; 1: Be polite\n\n&gt; 2: Posts to this subreddit must be requests for help learning python.\n\n&gt; 3: Replies on this subreddit must be pertinent to the question OP asked. \n\n&gt; 4: No replies copy / pasted from ChatGPT or similar.  \n\n&gt; 5: No advertising. No blogs/tutorials/videos/books/recruiting attempts.\n\n&gt; This means no posts advertising blogs/videos/tutorials/etc, no recruiting/hiring/seeking others posts. We're here to help, not to be advertised to. \n\n&gt; Please, no \"hit and run\" posts, if you make a post, engage with people that answer you. Please do not delete your post after you get an answer, others might have a similar question or want to continue the conversation.\n\n*****************************\n\n&gt; [**Learning resources**](#icon-information)\n\n&gt; Wiki and FAQ: [/r/learnpython/w/index](http://www.reddit.com/r/learnpython/wiki/index)\n\n*****************************\n\n&gt; [**Discord**](#icon-comments)\n\n&gt; [Join the Python Discord chat](https://discord.gg/python)",
            "submit_link_label": "",
            "user_flair_text_color": None,
            "restrict_commenting": False,
            "user_flair_css_class": None,
            "allow_images": False,
            "lang": "en",
            "whitelist_status": "all_ads",
            "url": "/r/learnpython/",
            "created_utc": 1254499181,
            "banner_size": None,
            "mobile_banner_image": "",
            "user_is_moderator": False,
            "allow_predictions_tournament": False
          }
        }
      ],
      "before": None
    }
  }

# console.log(file[0]['data']['children'][0]['data']['subscribers'])

print(file1["data"]["children"][0]["data"]["subscribers"])